version: '3.8'
services:
  backend:
    build: ./notnetflix-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://localhost:27017/notnetflix 

  frontend:
    build: ./notnetflix-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend